### ISSUE TITLE
Unable to load config with dependencies between YAML-derived pipelines

### ISSUE THREAD

**Issue by blalor** [tomzo/gocd-yaml-config-plugin#19]
I've just manually converted all of my pipelines from the monolithic cruise-config.xml to individual YAML files.  Upon restarting my server, the plugin is unable to load the config:

```
2017-01-11 14:52:23,206  WARN [104@MessageListener for ConfigMaterialUpdater] GoFileConfigDataSource:310 - Merged config update operation failed on LATEST 2 partials. Falling back to using LAST VALID 1 partials. Exception message was: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:142)
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:117)
    at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:77)
    at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:472)
    at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:399)
    at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:383)
    at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:304)
    at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:130)
    at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:116)
    at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:244)
    at com.thoughtworks.go.config.GoPartialConfig.updateConfig(GoPartialConfig.java:125)
    at com.thoughtworks.go.config.GoPartialConfig.onSuccessPartialConfig(GoPartialConfig.java:85)
    at com.thoughtworks.go.config.GoRepoConfigDataSource.notifySuccessListeners(GoRepoConfigDataSource.java:184)
    at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:153)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.updateConfigurationFromCheckout(ConfigMaterialUpdater.java:115)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:95)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:39)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:69)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
2017-01-11 14:52:23,235  WARN [104@MessageListener for ConfigMaterialUpdater] GoFileConfigDataSource:318 - Merged config update operation failed using fallback LAST VALID 2 partials. Exception message was: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:142)
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:117)
    at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:77)
    at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:472)
    at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:399)
    at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:383)
    at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:314)
    at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:130)
    at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:116)
    at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:244)
    at com.thoughtworks.go.config.GoPartialConfig.updateConfig(GoPartialConfig.java:125)
    at com.thoughtworks.go.config.GoPartialConfig.onSuccessPartialConfig(GoPartialConfig.java:85)
    at com.thoughtworks.go.config.GoRepoConfigDataSource.notifySuccessListeners(GoRepoConfigDataSource.java:184)
    at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:153)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.updateConfigurationFromCheckout(ConfigMaterialUpdater.java:115)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:95)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:39)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:69)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
2017-01-11 14:52:23,238  WARN [104@MessageListener for ConfigMaterialUpdater] GoFileConfigDataSource:331 - Configuration file is invalid: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
    at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:321)
    at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:130)
    at com.thoughtworks.go.config.GoConfigDao.updateConfig(GoConfigDao.java:116)
    at com.thoughtworks.go.server.service.GoConfigService.updateConfig(GoConfigService.java:244)
    at com.thoughtworks.go.config.GoPartialConfig.updateConfig(GoPartialConfig.java:125)
    at com.thoughtworks.go.config.GoPartialConfig.onSuccessPartialConfig(GoPartialConfig.java:85)
    at com.thoughtworks.go.config.GoRepoConfigDataSource.notifySuccessListeners(GoRepoConfigDataSource.java:184)
    at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:153)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.updateConfigurationFromCheckout(ConfigMaterialUpdater.java:115)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:95)
    at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:39)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:69)
    at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.thoughtworks.go.config.exceptions.GoConfigInvalidMergeException: 13+ errors :: "aci-packerizer :: build-aci :: build" tries to fetch artifact from pipeline "centos-aci-builder" which does not exist.;; Pipeline "centos-aci-builder" does not exist. It is used from pipeline "aci-packerizer".;; Pipeline with name 'centos-aci-builder' does not exist, it is defined as a dependency for pipeline 'aci-packerizer' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: plan :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-environment" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "tf-vm-images" which does not exist.;; "tf-env-ci :: apply :: plan" tries to fetch artifact from pipeline "aci-terraformer" which does not exist.;; Pipeline "tf-vm-images" does not exist. It is used from pipeline "tf-env-ci".;; Pipeline with name 'tf-vm-images' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'tf-environment' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; Pipeline with name 'aci-terraformer' does not exist, it is defined as a dependency for pipeline 'tf-env-ci' (git@example.com:myorg/gocd-pipelines-platform.git at cd0e50f0ababfc9e3a7b4b7fe3864896f8069b76);; 
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.validateCruiseConfig(MagicalGoConfigXmlLoader.java:142)
    at com.thoughtworks.go.config.MagicalGoConfigXmlLoader.preprocessAndValidate(MagicalGoConfigXmlLoader.java:117)
    at com.thoughtworks.go.config.MagicalGoConfigXmlWriter.write(MagicalGoConfigXmlWriter.java:77)
    at com.thoughtworks.go.config.GoFileConfigDataSource.configAsXml(GoFileConfigDataSource.java:472)
    at com.thoughtworks.go.config.GoFileConfigDataSource.getUnmergedConfig(GoFileConfigDataSource.java:399)
    at com.thoughtworks.go.config.GoFileConfigDataSource.trySavingConfig(GoFileConfigDataSource.java:383)
    at com.thoughtworks.go.config.GoFileConfigDataSource.writeWithLock(GoFileConfigDataSource.java:314)
    ... 13 more
2017-01-11 14:52:23,239  INFO [104@MessageListener for ConfigMaterialUpdater] GoConfigDao:121 - Config update request by anonymous is completed
```

It seems that dependencies between pipelines that are all defined in YAML cannot be loaded.

**Comment by tomzo** [comment]
Hi,

I am quite sure that dependencies work as they should. I'd recommend that you add pipelines to repository one by one, starting from most upstream. That way you can identify problems with your YAML early. 
Also I can probably help you, if you post some of your config.

**Comment by blalor** [comment]
@tomzo my sincere apologies: there were legitimate dependency errors.  I got a little lost when converting my configs and referenced stage names that didn't exist.
