### ISSUE TITLE
NPE if YAML File is Empty

### ISSUE THREAD

**Issue by birchb1024** [tomzo/gocd-yaml-config-plugin#82]
If a .gocd.yaml file is zero-length, the plugin fails with a null pointer exception. This kills all the pipelines, not just the bad one. 

- Go Version: 17.12.0

Here's the logs:

```
go-server.log:java.lang.RuntimeException: Interaction with plugin with id 'yaml.config.plugin' implementing 'configrepo' extension failed while requesting for 'parse-directory'. Reason: [The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '{"target_version":1,"environments":[],"pipelines":[],"errors":[{"location":"YAML config plugin","message":"java.lang.NullPointerException"}]}']
```

```
2018-10-15 15:55:50,613 ERROR [90@MessageListener for ConfigMaterialUpdater] YamlConfigPlugin:82 - Unexpected error occurred in YAML configuration plugin.
java.lang.NullPointerException: null
        at cd.go.plugin.config.yaml.transforms.RootTransform.transform(RootTransform.java:32)
        at cd.go.plugin.config.yaml.YamlFileParser.parseFiles(YamlFileParser.java:30)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.handleParseDirectoryRequest(YamlConfigPlugin.java:107)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.handle(YamlConfigPlugin.java:70)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:167)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager$2.execute(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:316)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:246)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:162)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.configrepo.ConfigRepoExtension.parseDirectory(ConfigRepoExtension.java:55)
        at com.thoughtworks.go.config.ConfigRepoPlugin.parseDirectory(ConfigRepoPlugin.java:56)
        at com.thoughtworks.go.config.ConfigRepoPlugin.load(ConfigRepoPlugin.java:46)
        at com.thoughtworks.go.config.GoRepoConfigDataSource.onCheckoutComplete(GoRepoConfigDataSource.java:136)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.updateConfigurationFromCheckout(ConfigMaterialUpdater.java:106)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:87)
        at com.thoughtworks.go.server.materials.ConfigMaterialUpdater.onMessage(ConfigMaterialUpdater.java:38)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:73)
        at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:53)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by kshav19** [comment]
Anyone fixing this ??

**Comment by tomzo** [comment]
I'll push a fix in a moment. 
Empty file will be treated as an error.

**Comment by tomzo** [comment]
@kshav19 which plugin version are you using?
I have added a test to reproduce this, but there is a nice error message saying that file is empty.
