### ISSUE TITLE
Config repo preflight check fails with java.lang.ClassCastException

### ISSUE THREAD

**Issue by rajiesh** [tomzo/gocd-yaml-config-plugin#97]
Plugin version: 0.8.4
GoCD Server version: 19.1.0 (8362-a2ac7ed2764cf3b922afbde7a7b4c75a3653c5ff)

Perform preflight check for any valid pipeline configuration in yaml ,

`curl -H 'Accept: application/vnd.go.cd.v1+json'   -F 'files[]=pipeline-gocd.yaml'   "http://<go-server>:8153/go/api/admin/config_repo_ops/preflight?pluginId=yaml.config.plugin"`

Plugin logs below error,

```
2019-01-10 16:19:34,157 ERROR [qtp1728790703-16] YamlConfigPlugin:128 - Unexpected error occurred in YAML configuration plugin.
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at cd.go.plugin.config.yaml.transforms.RootTransform.transform(RootTransform.java:40)
        at cd.go.plugin.config.yaml.YamlConfigParser.parseStream(YamlConfigParser.java:45)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.lambda$null$0(YamlConfigPlugin.java:111)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.lambda$handleParseContentRequest$1(YamlConfigPlugin.java:108)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.handlingErrors(YamlConfigPlugin.java:189)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.handleParseContentRequest(YamlConfigPlugin.java:102)
        at cd.go.plugin.config.yaml.YamlConfigPlugin.handle(YamlConfigPlugin.java:69)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:225)
        at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
        at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
        at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
        at com.thoughtworks.go.plugin.access.configrepo.ConfigRepoExtension.parseContent(ConfigRepoExtension.java:121)
        at com.thoughtworks.go.config.ConfigRepoPlugin.parseContent(ConfigRepoPlugin.java:77)
        at com.thoughtworks.go.apiv1.configrepooperations.ConfigRepoOperationsControllerV1.preflight(ConfigRepoOperationsControllerV1.java:119)
```

**Comment by tomzo** [comment]
@marques-work can you take a look at this?

**Comment by bytefukr** [comment]
@tomzo sure, I'll look at this now

**Comment by bytefukr** [comment]
@rajiesh you might be missing the `@` symbol for multipart upload. right now you are not sending the file content, but rather the text `pipeline-gocd.yaml` as the content to preflight.

The `-F` flag should look like this: `-F 'files[]=@relpath/to/pipeline-gocd.yaml` (notice the `@` symbol preceding)

**Comment by marques-work** [comment]
@tomzo sure, I'll look at this now

@rajiesh you might be missing the @ symbol for multipart upload. right now you are not sending the file content, but rather the text pipeline-gocd.yaml as the content to preflight.

The -F flag should look like this: -F 'files[]=@relpath/to/pipeline-gocd.yaml (notice the @ symbol preceding)

**Comment by rajiesh** [comment]
@marques-work Thanks for pointing it out, yes I missed it while preparing the curl command. Sorry for raising a wrong issue. Closing the issue
